# Generated by Django 5.2 on 2025-05-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='document_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='offer_used',
            field=models.CharField(blank=True, default='Basic', help_text='e.g., Basic, Premium', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ongoing_status',
            field=models.CharField(blank=True, help_text='e.g., Active subscription, Pending review', max_length=100, null=True),
        ),
    ]
