# Generated by Django 5.2 on 2025-05-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_bio_remove_userprofile_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='offer_used',
            field=models.CharField(blank=True, default='Basic', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ongoing_status',
            field=models.CharField(blank=True, help_text='e.g., Active subscription', max_length=100, null=True),
        ),
    ]
