# Generated by Django 5.2 on 2025-05-25 12:26

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_profile_picture_userimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_file', models.FileField(upload_to=accounts.models.user_document_path)),
                ('category', models.CharField(choices=[('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('CONTRACT', 'Contract'), ('HOME_PLAN', 'Home Plan'), ('INSURANCE', 'Insurance'), ('BANK_STATEMENT', 'Bank Statement'), ('UTILITY_BILL', 'Utility Bill'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(blank=True, help_text='Year associated with the document (e.g., tax year, bill year)', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_type', models.CharField(blank=True, choices=[('EXPENSE', 'Expense'), ('GAIN', 'Gain'), ('INFO', 'Informational')], default='INFO', max_length=10, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.userprofile')),
            ],
        ),
    ]
