# Generated by Django 5.2 on 2025-05-25 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.IntegerField(blank=True, help_text='Year associated with the document', null=True),
        ),
        migrations.CreateModel(
            name='ManualTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('SALARY', 'Salary'), ('RENT', 'Rent Payment'), ('GROCERIES', 'Groceries'), ('TRANSPORT', 'Transport'), ('ENTERTAINMENT', 'Entertainment'), ('INVESTMENT', 'Investment'), ('OTHER_EXPENSE', 'Other Expense'), ('OTHER_INCOME', 'Other Income'), ('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('CONTRACT', 'Contract'), ('HOME_PLAN', 'Home Plan'), ('INSURANCE', 'Insurance'), ('BANK_STATEMENT', 'Bank Statement'), ('UTILITY_BILL', 'Utility Bill'), ('OTHER', 'Other')], default='OTHER_EXPENSE', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_type', models.CharField(choices=[('EXPENSE', 'Expense'), ('GAIN', 'Gain'), ('INFO', 'Informational')], max_length=10)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_transactions', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
