# Generated by Django 5.2 on 2025-05-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_document_year_manualtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='document_count',
            field=models.IntegerField(default=0),
        ),
    ]
